
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.12.0"
criteria = "safe-to-deploy"
